BEGIN;

CREATE TABLE IF NOT EXISTS security.security_logs (
    id BIGINT GENERATED ALWAYS AS IDENTITY,

    uuid UUID NOT NULL DEFAULT uuidv7(),

    user_id BIGINT,

    event_type VARCHAR(50) NOT NULL,

    severity security_severity_enum NOT NULL DEFAULT 'info',

    ip_address INET NOT NULL,

    endpoint VARCHAR(255),

    http_method VARCHAR(10),

    status_code SMALLINT,

    user_agent TEXT,

    metadata JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_security_logs
        PRIMARY KEY (id),

    CONSTRAINT uq_security_logs_uuid
        UNIQUE (uuid),

    CONSTRAINT fk_security_logs_user
        FOREIGN KEY (user_id)
        REFERENCES core.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT ck_security_logs_status_code
        CHECK (
            status_code IS NULL
            OR status_code BETWEEN 100 AND 599
        )
);

COMMENT ON TABLE security.security_logs IS
'Stores security-related events generated by the application.';

COMMENT ON COLUMN security.security_logs.id IS
'Internal primary key.';

COMMENT ON COLUMN security.security_logs.uuid IS
'Public unique identifier (UUID v7).';

COMMENT ON COLUMN security.security_logs.user_id IS
'User associated with the security event, if available.';

COMMENT ON COLUMN security.security_logs.event_type IS
'Security event type.';

COMMENT ON COLUMN security.security_logs.severity IS
'Severity level of the security event.';

COMMENT ON COLUMN security.security_logs.ip_address IS
'Origin IP address.';

COMMENT ON COLUMN security.security_logs.endpoint IS
'Requested endpoint.';

COMMENT ON COLUMN security.security_logs.http_method IS
'HTTP method used.';

COMMENT ON COLUMN security.security_logs.status_code IS
'HTTP response status code.';

COMMENT ON COLUMN security.security_logs.user_agent IS
'Client user agent string.';

COMMENT ON COLUMN security.security_logs.metadata IS
'Additional security metadata.';

COMMENT ON COLUMN security.security_logs.created_at IS
'Timestamp when the event occurred.';

COMMIT;
